# Generated by Django 3.2.4 on 2021-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='danish@localhost.com', max_length=254),
            preserve_default=False,
        ),
    ]
